name: "Chore Trade"
description: "Multiuser household chore tracking with balanced economy, brownie points and a reward system"
version: "0.1.00004"
slug: "choretrade"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
