name: "Chore Trade"
description: "Multiuser household chore tracking with balanced economy, brownie points and a reward system"
version: "0.1.00005"
slug: "choretrade"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int
